Invite Codes
csi4999-panic-button/panic-button pull request #16
Opened 2017-10-17 21:51 UTC by tcarrio

Some of the methods for invite codes such as rotating a code, deleting codes, getting your codes (based on if you are the teacher of the class it relates to)

2017-10-18 00:06 UTC, tcarrio commented
Didn't use the same return structure in the Promise block on DELETE / PUT due to needing the variable from the outer Promise as well

2017-10-19 00:04 UTC, dyladan requested changes

2017-10-19 00:04 UTC, dyladan commented on src/server/routes/api/invite-codes/index.js
> +        }).then( classroom => {
classroom undefined

2017-10-19 00:04 UTC, dyladan commented on src/server/routes/api/invite-codes/index.js
> +            ]}).then( classroom => classroom )
identity function does nothing

2017-10-19 00:04 UTC, dyladan commented on src/server/util/index.js
>  }
no newline at the end? you monster ;)

2017-10-24 22:51 UTC, tcarrio commented
Worked through **multiple** implementations of the `populate` method. This one makes the least sense code-wise yet has 2 out of 3 codes populated whereas the other methods I tried resulted in entirely nulls. 

![CodeDoesntWork.jpg](https://cdn.meme.am/cache/instances/folder367/45770367.jpg)

2017-11-02 21:10 UTC, tcarrio commented
Alright, this one looks all good to go now. Fixed `POST /classrooms`, `PUT /classrooms/id`, `POST ../join`, `PUT /classroomId/code/type` (basically all 4 hard routes for classrooms routes). 

Changes include: **Everything**.

Even the schema changed.

2017-11-05 17:30 UTC, dyladan requested changes

2017-11-05 17:30 UTC, dyladan commented on src/server/models/invite-codes.js
>  class InviteCode {
You can keep the class stuff if you want but since we never query codes again it is unused

2017-11-05 17:30 UTC, dyladan commented on src/server/routes/api/classrooms/index.js
> +    .then( c => res.json(c.sanitize(req.user)))
putting `.then` and `.catch` inside try/catch blocks is an anti-pattern. It prevents the try/catch block from functioning properly. See pull request #22

2017-11-05 17:30 UTC, dyladan commented on src/server/routes/api/classrooms/index.js
>      res.status(401).send();
Have to return here or the code beneath it will still run and cause problems

2017-11-05 17:30 UTC, dyladan commented on src/server/routes/api/classrooms/index.js
>      res.status(401).send();
See pull request #23

2017-11-05 17:30 UTC, dyladan commented on src/server/routes/api/classrooms/index.js
> +      return res.json({ success: true, message: "User is not a " + req.params.type + " of the classroom" });
The success message here makes no sense

2017-11-05 17:30 UTC, dyladan commented on src/server/routes/index.js
> +    }).then( user => {
This is more of the same anti-pattern

2017-11-05 18:43 UTC, dyladan approved these changes

2017-11-05 18:44 UTC, merged